"""Generate the sequential job graph; a matrix cannot pass build state in order."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHECKOUT = "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6"
PYTHON = "actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6"
DOWNLOAD = "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8"


def generate():
    config = json.loads((ROOT / "config.json").read_text())
    count = config["build_stages"]
    if not 1 <= count <= 32:
        raise ValueError("build_stages must be between 1 and 32")
    header = f"""# Generated by scripts/generate_workflow.py. Edit the generator or config.json.
name: Sync Brave, build Windows x64, release
on:
  schedule:
    - cron: '23 4 * * *'
  workflow_dispatch:
    inputs:
      upstream_tag:
        description: 'Optional published Brave tag, e.g. v1.99.8 (blank tracks configured channel)'
        type: string
        default: ''
      resume_run_id:
        description: 'Optional earlier build run containing a compatible checkpoint; requires upstream_tag'
        type: string
        default: ''
      resume_stage:
        description: 'Checkpoint number in resume_run_id'
        type: number
        default: 0
  push:
    branches: [main]
    paths: ['.gitattributes', 'config.json', 'patches/**', 'scripts/**', 'updater/**', 'installer/**', '.github/workflows/**']
permissions:
  contents: read
  actions: write
concurrency:
  group: browser-release
  cancel-in-progress: false
jobs:
  detect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
"""
    keys = ["build", "upstream_tag", "upstream_sha", "release_tag", "patch_digest",
            "channel", "prerelease", "runner", "node_version", "pnpm_version"]
    for key in keys:
        header += f"      {key}: ${{{{ steps.resolve.outputs.{key} }}}}\n"
    header += f"""    steps:
      - uses: {CHECKOUT}
        with:
          persist-credentials: false
      - uses: {PYTHON}
        with:
          python-version: '3.13'
      - name: Select new upstream release
        id: resolve
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          UPSTREAM_TAG: ${{{{ inputs.upstream_tag }}}}
          RESUME_RUN_ID: ${{{{ inputs.resume_run_id }}}}
        run: python scripts/upstream.py --tag "$UPSTREAM_TAG"
  extension-service:
    needs: detect
    if: needs.detect.outputs.build == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: {CHECKOUT}
        with:
          persist-credentials: false
      - uses: {PYTHON}
        with:
          python-version: '3.13'
      - name: Check original Brave-hosted uBlock download
        env:
          BRAVE_SERVICES_KEY: ${{{{ secrets.BRAVE_SERVICES_KEY }}}}
          UPSTREAM_TAG: ${{{{ needs.detect.outputs.upstream_tag }}}}
        run: python scripts/extension_services.py --tag "$UPSTREAM_TAG"
  patches:
    needs: detect
    if: needs.detect.outputs.build == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: {CHECKOUT}
        with:
          persist-credentials: false
      - uses: {PYTHON}
        with:
          python-version: '3.13'
      - name: Replay patches on selected upstream
        env:
          UPSTREAM_TAG: ${{{{ needs.detect.outputs.upstream_tag }}}}
          UPSTREAM_SHA: ${{{{ needs.detect.outputs.upstream_sha }}}}
        run: python scripts/prepare.py --root "$RUNNER_TEMP/patch-check" --tag "$UPSTREAM_TAG" --sha "$UPSTREAM_SHA" --patch-only
  prepare:
    needs: [detect, patches, extension-service]
    uses: ./.github/workflows/windows-stage.yml
    secrets:
      BRAVE_SERVICES_KEY: ${{{{ secrets.BRAVE_SERVICES_KEY }}}}
    with:
      mode: ${{{{ inputs.resume_run_id != '' && 'compile' || 'prepare' }}}}
      stage: 0
      previous_stage: ${{{{ fromJSON(format('{{0}}', inputs.resume_stage || 0)) }}}}
      checkpoint_run_id: ${{{{ inputs.resume_run_id }}}}
      upstream_tag: ${{{{ needs.detect.outputs.upstream_tag }}}}
      upstream_sha: ${{{{ needs.detect.outputs.upstream_sha }}}}
      release_tag: ${{{{ needs.detect.outputs.release_tag }}}}
      channel: ${{{{ needs.detect.outputs.channel }}}}
      runner: ${{{{ needs.detect.outputs.runner }}}}
      node_version: ${{{{ needs.detect.outputs.node_version }}}}
      pnpm_version: ${{{{ needs.detect.outputs.pnpm_version }}}}
"""
    for stage in range(1, count + 1):
        previous = "prepare" if stage == 1 else f"build-{stage - 1}"
        header += f"""  build-{stage}:
    needs: [detect, {previous}]
    uses: ./.github/workflows/windows-stage.yml
    secrets:
      BRAVE_SERVICES_KEY: ${{{{ secrets.BRAVE_SERVICES_KEY }}}}
    with:
      mode: compile
      stage: {stage}
      previous_stage: {stage - 1}
      finished: ${{{{ needs.{previous}.outputs.finished }}}}
      upstream_tag: ${{{{ needs.detect.outputs.upstream_tag }}}}
      upstream_sha: ${{{{ needs.detect.outputs.upstream_sha }}}}
      release_tag: ${{{{ needs.detect.outputs.release_tag }}}}
      channel: ${{{{ needs.detect.outputs.channel }}}}
      runner: ${{{{ needs.detect.outputs.runner }}}}
      node_version: ${{{{ needs.detect.outputs.node_version }}}}
      pnpm_version: ${{{{ needs.detect.outputs.pnpm_version }}}}
"""
    header += f"""  release:
    needs: [detect, build-{count}]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      actions: write
    steps:
      - uses: {CHECKOUT}
        with:
          persist-credentials: false
      - name: Require completed compilation
        env:
          FINISHED: ${{{{ needs.build-{count}.outputs.finished }}}}
        run: test "$FINISHED" = true
      - uses: {DOWNLOAD}
        with:
          name: browser-release
          path: dist
      - name: Check release payload
        env:
          RELEASE_TAG: ${{{{ needs.detect.outputs.release_tag }}}}
          UPSTREAM_SHA: ${{{{ needs.detect.outputs.upstream_sha }}}}
          PATCH_DIGEST: ${{{{ needs.detect.outputs.patch_digest }}}}
        run: python scripts/verify_release.py dist
      - name: Publish immutable release
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          RELEASE_TAG: ${{{{ needs.detect.outputs.release_tag }}}}
          UPSTREAM_TAG: ${{{{ needs.detect.outputs.upstream_tag }}}}
          CHANNEL: ${{{{ needs.detect.outputs.channel }}}}
          PRERELEASE: ${{{{ needs.detect.outputs.prerelease }}}}
        shell: bash
        run: |
          set -euo pipefail
          flags=()
          if [ "$PRERELEASE" = true ]; then flags+=(--prerelease --latest=false); fi
          if gh release view "$RELEASE_TAG" --json isDraft > "$RUNNER_TEMP/release.json"; then
            python -c 'import json,sys; assert json.load(open(sys.argv[1]))["isDraft"], "Refusing to overwrite published release"' "$RUNNER_TEMP/release.json"
          else
            gh release create "$RELEASE_TAG" --target "$GITHUB_SHA" --draft "${{flags[@]}}" \\
              --title "Brave Chrome Sync [$CHANNEL] $UPSTREAM_TAG" --notes-file dist/release-notes.md
          fi
          gh release upload "$RELEASE_TAG" dist/*.exe dist/*.zip dist/*.tar.gz dist/*.ps1 dist/*.json dist/LICENSE dist/SHA256SUMS --clobber
          gh release edit "$RELEASE_TAG" --draft=false "${{flags[@]}}"
      - name: Remove published build artifact
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: python scripts/cleanup_artifacts.py --name browser-release
"""
    return header


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / ".github/workflows/build-release.yml"
    expected = generate()
    if args.check:
        if output.read_text(encoding="utf-8") != expected:
            raise SystemExit("Generated workflow is stale. Run python scripts/generate_workflow.py")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
